langchain4j:
  open-ai:
    chat-model:
      # ???? KEY?????????? KEY
      api-key: sk-xxx
      model-name: qwen-turbo
      # ????OpenAI?????base_url?https://dashscope.aliyuncs.com/compatible-mode/v1
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
